using UnityEngine;
using UnityEngine.SceneManagement;
using System.Collections;

public class Jaspocalypse : Enemy
{
    
    [SerializeField]
    float minrange = 3f;

    [SerializeField]
    float maxrange = 7f;

    [SerializeField]
    GameObject pullObject;

    [SerializeField]
    GameObject Shockwave;

    [SerializeField]
    GameObject smashCollider;

    Animator anim;

    private new void Awake()
    {
        base.Awake();
        anim = GetComponent<Animator>();
        StartCoroutine(Smash());
    }
    
    private void Update()
    {
        if (Vector3.Distance(transform.position, Player.instance.transform.position) > minrange)
        {

            Vector3 direction = (Player.instance.transform.position - transform.position).normalized;
            transform.position += direction * Time.deltaTime * speed;
            transform.position = new Vector2(transform.position.x, .5f);
            //anim.SetBool("walking", true);
        }
        else
        {

            anim.SetBool("walking", false);
            

        }

        if (Vector3.Distance(transform.position, Player.instance.transform.position) > maxrange)
        {

            PullPlayer();
        }


    }

    private void PullPlayer()
    {
        StartCoroutine(Player.instance.GetComponent<PlayerPlatformerController>().GetPulled((transform.position - Player.instance.transform.position)));
        Instantiate(pullObject, transform).transform.position += Vector3.right * 5 + Vector3.down;
    }
    
    
    IEnumerator Smash()
    {
        
        while (true)
        {
            yield return new WaitForSeconds(1f);

            if (Vector3.Distance(transform.position, Player.instance.transform.position) < minrange)
            {

                anim.SetTrigger("smash");
                yield return new WaitForSeconds(.1f);
                Instantiate(smashCollider, transform);

                yield return new WaitForSeconds(.3f);


            }
            else if(Vector3.Distance(transform.position, Player.instance.transform.position) > minrange && Vector3.Distance(transform.position, Player.instance.transform.position) < maxrange)
            {

                anim.SetBool("walking", false);

                anim.SetTrigger("smashdown");
                yield return new WaitForSeconds(.2f);

                GameObject go = Instantiate(Shockwave, transform);
                go.transform.parent = null;
                go.GetComponent<Shockwave>().SetDirection(true);

                go = Instantiate(Shockwave, transform);
                go.transform.parent = null;
                go.GetComponent<Shockwave>().SetDirection(false);


                yield return new WaitForSeconds(.3f);
            }
            else
            {

            }

            anim.SetBool("walking", true);
        }



    }

    protected override void Die()
    {
        base.Die();
        SceneManager.LoadScene("AutoGeneratedLevels");
    }

}
